# Generated by Django 3.1.4 on 2021-02-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='friends',
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
