# Generated by Django 3.1.4 on 2021-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210214_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
