# Generated by Django 3.1.4 on 2021-02-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210214_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='username',
        ),
    ]
