# Generated by Django 3.1.4 on 2021-02-14 15:29

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210214_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[chat.models.validate_length]),
        ),
    ]
